imports:
  SS:
    standard_name: tba1
    options:
      convert2MAPL: 1
      state: 'export'
    policies:
      TransferOfferGeomObject: 'can provide'
      SharePolicyField:        'share'
      SharePolicyGeomObject:   'share'
    tracer:
      name: 'inst_mass_tracers'
      entries: [seas1, seas2, seas3, seas4, seas5]
  FROCEAN:
    standard_name: tba2
    options:
      convert2MAPL: 1
      state: 'import'
    policies:
      TransferOfferGeomObject: 'can provide'
      SharePolicyField:        'share'
      SharePolicyGeomObject:   'share'

tracers:
  inst_mass_tracers:
    field_table: 'field_table'
