imports:
  SS:
    standard_name: tba1
    state: 'export'
    options:
      convert2MAPL: 1.0
    policies:
      TransferOfferGeomObject: 'can provide'
      SharePolicyField:        'share'
      SharePolicyGeomObject:   'share'
    tracer:
      name: 'inst_mass_tracers'
      entries: [seas1, seas2, seas3, seas4, seas5]

  FROCEAN:
    standard_name: tba2
    state: 'import'
    options:
      convert2MAPL: 1.0
    policies:
      TransferOfferGeomObject: 'can provide'
      SharePolicyField:        'share'
      SharePolicyGeomObject:   'share'

tracers:
  inst_mass_tracers:
    field_table: 'field_table'


  configuration_name:
    field_name: 'inst_mass_tracers'
    field_table_filename: 'field_table'
